[package]
name = "tfjs-backend-wasm"
version = "0.1.0"
authors = ["Nikhil Thorat <nsthorat@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]
